name: Build

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        architecture:
          [
            "x86-linux-gnu",
            "x86-linux-musl",
            "x86_64-linux-gnu",
            "x86_64-linux-musl",
          ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.2316+ac2930332

      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.architecture }} -Doptimize=ReleaseFast
          mv zig-out/bin/Tez ./${{ matrix.architecture }}

      - name: update release
        id: update_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.update_release.outputs.upload_url }}
          asset_path: ./${{ matrix.architecture }}
          asset_name: ${{ matrix.architecture }}
          asset_content_type: application/octet-stream
