name: Build

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        architecture:
          [
            "x86-linux-gnu",
            "x86-linux-musl",
            "x86_64-linux-gnu",
            "x86_64-linux-musl",
          ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.2316+ac2930332

      - name: Test
        run: |
          zig build -Dtarget=${{ matrix.architecture }} -Doptimize=ReleaseFast test --summary all
